### ISSUE TITLE
Alte Rolle wird nicht entfernt

### ISSUE THREAD

**Issue by SimuPlays** [Kaktushose/levelbot2#13]
**Beschreibe den Bug**
Bei einem Levelaufstieg wird die vorherige Rolle nicht entfernt.

**Schritte zum Reproduzieren**
Siehe Skygamer, hat nun Welcome und Bronze.
Dieser Bug könnte in Zusammenhang mit der ständigen Neuvergabe der Welcome-Rolle stehen.
Es scheint Probleme mit den Rollenzuweisungen im Allgemeinen zu geben.

**Comment by SkyGamer24** [comment]
Da mich KaktusHose hier her verwiesen hat, es nicht das Problem, dass ich die Bronze Rolle noch habe, sondern dass ich die Silber Rolle nicht habe obwohl ich über 400 XPs habe...

**Comment by Kaktushose** [comment]
Wollte nur sagen, dass es auch weitere Probleme gibt, nicht, dass du deinen bug hier noch mal schildern sollst

**Comment by SkyGamer24** [comment]
Achso sorry

**Comment by Kaktushose** [comment]
Bug ist anscheinend auf die Welcome Rolle einzugrenzen. 

1. User wird Bronze.
2. Welcome wird entfernt
3. Bronze wird vergeben
4. Welcome wird erneut vergeben

**Comment by Kaktushose** [comment]
Hierbei handelt es sich um keinen Bug des Levelbots. Der Fehler konnte auf der Testguild nicht reproduziert werden. Außerdem wurde die Welcome Rolle nach manueller Entfernung wieder hinzugefügt, obwohl der Bot offline war
