### ISSUE TITLE
Kaufen-Befehl durch fremde User bedienbar

### ISSUE THREAD

**Issue by SimuPlays** [Kaktushose/levelbot2#19]
**Beschreibe den Bug**
Der Kaufen-Befehl kann durch Reaktionen von fremden Usern für den User genutzt werden, der !kaufen eingegeben hat. Damit können fremde User Items erwerben. 
Der Bot soll nur durch Reaktionen vom User selbst reagieren, ansonsten ist ein Missbrauch sehr leicht möglich!

**Comment by Kaktushose** [comment]
ReactionWaiter refactoren ggf. rewriten
