### ISSUE TITLE
Geschenkte Items automatisch aufaddieren, wenn man dieses bereits besitzt.

### ISSUE THREAD

**Issue by SimuPlays** [Kaktushose/levelbot2#24]
Das Geschenkte Item soll nach dem aktuellen automatisch aufaddiert statt überschrieben werden.

**Comment by Kaktushose** [comment]
Was verstehst du unter angehängt? Soll nach dem Item das geschenkte aktiviert werden oder soll es aufaddiert werden?
Im Moment wird glaube ich das Item überschrieben

**Comment by Kaktushose** [comment]
Ja, das Item wird überschrieben

**Comment by SimuPlays** [comment]
Überschrieben ist schlecht. Am Besten das Geschenkte nach dem aktuellen automatisch Aktivieren. Dann ist es am Cleansten.

**Comment by Kaktushose** [comment]
Das automatische aktivieren danach wird schwierig. Ein einfach aufaddieren wäre besser

**Comment by SimuPlays** [comment]
Wird dann die neue Dauer auch bei !info angezeigt?

**Comment by SimuPlays** [comment]
Ist in Ordnung.
