### ISSUE TITLE
XP und Münzen abhängig vom Rang

### ISSUE THREAD

**Issue by SkyGamer24** [Kaktushose/levelbot2#27]
Ich würde es toll finden, wenn man z.B. die Münzen wahrscheinlichkeit abhängig pro Rank macht, dass man mit Welcome 0-5/Nachricht, Bronze 1-5/Nachricht, Silber 2-5/Nachricht, etc bekommt.

Eventuell, dass man mit Welcome 0-1/Nachricht, Bronze 0-2/Nachricht, Silber 0-3/Nachricht bekommt.

Das selbe gilt für XP´s.

Des weiteren wäre es toll, wenn ihr den 0er bei den Münzen auf 1 erhöht, dass man mindestens 1 Münze pro Nachricht bekommt!

**Comment by Kaktushose** [comment]
Das würde es am Anfang sehr schwer machen, und gegen Ende hin immer leichter. Finde ich nicht so gut. 
Die 0 Münzen finde ich als Abwechslung recht interessant, aber da kann @SimuPlays mehr zu sagen

**Comment by SimuPlays** [comment]
Erster Vorschlag: Abgelehnt.
Zum Zweiten: Wunsch ist zur Kenntnis genommen, ob er umgesetzt wird werden wir bei den nächsten Balance-Changes überlegen.
