### ISSUE TITLE
!version wird nicht in !hilfe angezeigt

### ISSUE THREAD

**Issue by 1Flo3** [Kaktushose/levelbot2#29]
**Bug**
Folgende Commands stehen zur Verfügung. !info, !kaufen. !hilfe <command> für Details

**Schritte zum Reproduzieren**
!hilfe

**Erwartetes Verhalten**
Folgende Commands stehen zur Verfügung. !info, !kaufen, !version. !hilfe <command> für Details

**Screenshots**
keine

**Discordname + Discriminator**
nicht relevant

**Comment by Kaktushose** [comment]
hilfe wird eh bald überarbeitet. siehe #30
