### ISSUE TITLE
Automatische Rollenzuweisung

### ISSUE THREAD

**Issue by SkyGamer24** [Kaktushose/levelbot2#35]
Trotz meinen 400 XPs bin ich immer noch Bronze statt Silber. 

Vielleicht liegt es daran, dass ich 200XPs durch den Boost erhalten habe, die nicht zählen? 

Wäre toll wenn der Fehler beseitigt wird, und ich dir Silber Rolle erhalte. 

**Dein Discordname + Discriminator**
SkyGamer #0001

**Comment by Kaktushose** [comment]
Mit dem Booster hängt das nicht zusammen. Es scheint ein generelles Problem mit der Rollenzuweisung zu geben. Siehe #13

**Comment by Kaktushose** [comment]
Es handelt sich um keinen Fehler, die Grenze war nur auf 500 gestellt. Ist behoben.
