### ISSUE TITLE
Kaufdatum 1970 bei nicht-gekauften Items

### ISSUE THREAD

**Issue by Lukas283** [Kaktushose/levelbot2#47]
Bei dem Münzenbooster, welchen ich durch denn Stufenaufstieg zu Gold erhalten habe, wird als Kaufdatum wieder der 1. Jänner 1970 angezeigt.

Schritte zum Reproduzieren: Münzenbooster durch Stufenaufstieg erhalten und warten, bis er abläuft

Ich hätte erwartet, dass das Datum und die Uhrzeit, an dem ich ihn erhalten habe, angezeigt wird.

Lukas.#3620

**Comment by Kaktushose** [comment]
Bereits durch #24 gefixt. Trotzdem vielen Dank für den Report
