### ISSUE TITLE
Rechtschreibfehler in Fehlermeldung

### ISSUE THREAD

**Issue by Kaktushose** [Kaktushose/levelbot2#51]
**Beschreibe den Bug**
In der Fehlermeldung (siehe Anhang) steht `ausgschlossen` anstatt `ausgeschlossen`. 

**Schritte zum Reproduzieren**
!info @Bot

**Screenshots**
![image](https://user-images.githubusercontent.com/42280757/78512091-06295200-77a2-11ea-9182-23e97e1b9779.png)

**Dein Discordname + Discriminator**
Kaktushose#0436

**Comment by Lukas283** [comment]
Vielen Dank, mit diesem Bug kann man das Level System ja kaum nutzen. :D
