### ISSUE TITLE
Items für andere kaufen und entfernen

### ISSUE THREAD

**Issue by SimuPlays** [Kaktushose/levelbot2#7]
**Steht dein Feature-Wunsch im Zusammenhang mit einem Problem? Bitte beschreibe es.**
Moderatoren können für andere User bisher keine Items hinzufügen bzw. entfernen.

**Beschreibe die Lösung, die du gerne hättest**
Befehl !kaufen, dann User auswählen und das Item für ihn erwerben. Ausgenommen Premium Unlimited. Dieses soll über den Befehl !kaufen premium unlimited @Username gekauft und auch wieder entfernt werden können. Lösung für entfernen anderer Items suchen! Gerade zu Testzwecken ist es hilfreich, wenn man Items auch wieder entfernen kann.

**Comment by SimuPlays** [comment]
Achtung: Items kaufen für andere nur durch das Team, nicht von anderen Usern!!!

**Comment by SimuPlays** [comment]
Für mich wäre dieses Feature übrigens durchaus von höherer Bedeutung, sobald die wesentlichen Bugs gefixt sind (also noch vor anderen neuen Features).

**Comment by Kaktushose** [comment]
Aufgrund von anderen Bugs zu Version 2.1.0 verschoben
